name: Android Built

on:
  push:
    branches:
      - master



jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Use Java8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build debug apk
        run: ./gradlew clean assembleDebug

      - name: Create release and upload apk
        uses: underwindfall/create-release-with-debugapk@v2.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v1.0.0
          asset_path: app/build/outputs/apk/debug/app-debug.apk
          asset_name: Example.apk
          asset_content_type: application/zip
#
#
#jobs:
#  build:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v1
#      - name: set up JDK 11
#        uses: actions/setup-java@v1
#        with:
#          java-version: 11
#      - name: Make Gradle executable
#        run: chmod +x ./gradlew
#      - name: Build with Gradle
#        run: ./gradlew build
#      - name: Build Debug APK
#        run: ./gradlew assembleDebug
#      - name: Releasing using Hub
#        uses: ShaunLWM/action-release-debugapk@master
#        env:
#          GITHUB_TOKEN: ${{ secrets.TOKEN }}
#          APP_FOLDER: app
#          RELEASE_TITLE: New Build
#
#jobs:
#  test:
#    name: Run Unit Tests
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v1
#      - name: Setup JDK
#        uses: actions/setup-java@v1
#        with:
#          java-version: 11
#      - name: Run Tests
#        run: bash ./gradlew test --stacktrace
#
#  apk:
#    name: Generate APK
#    needs: test
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v1
#      - name: Setup JDK
#        uses: actions/setup-java@v1
#        with:
#          java-version: 11
#      - name: Build APK
#        run: bash ./gradlew assembleDebug --stacktrace
#      - name: Upload APK
#        uses: actions/upload-artifact@v1
#        with:
#          name: apk
#          path: app/build/outputs/apk/debug/app-debug.apk
#
#
#  release:
#    name: Release APK
#    needs: apk
#    runs-on: ubuntu-latest
#    steps:
#      - name: Download APK from build
#        uses: actions/download-artifact@v1
#        with:
#          name: apk
#      - name: Create Release
#        id: create_release
#        uses: actions/create-release@v1
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          tag_name: ${{ github.ref }}
#          release_name: Release Version 1